name: 'Deploy ecs service'
description: 'Deploys a service again with the latest container'
inputs:
  service:
    description: 'The name of the ECS service to deploy to.'
    required: true 
  cluster:
    description: "The name of the ECS service's cluster.  Will default to the 'default' cluster"
    required: true 
runs:
  using: 'node12'
  main: 'dist/index.js'
